### ISSUE TITLE
Support latest edge version 

### ISSUE THREAD

**Issue by mspiess** [sitespeedio/edgedriver#20]
Currently there is no way to download version 117.

**Comment by soulgalore** [comment]
Hi @mspiess I can fix a release tonight. It should work with setting the edgedriver version as env variable, have you tried?

> You can download another Edgedriver version by setting process.env.EDGEDRIVER_VERSION.
`EDGEDRIVER_VERSION=81.0.4044.20 node install.js`

**Comment by mspiess** [comment]
Hi @soulgalore ,
Thanks for the quick response. Yes, I tried setting the version as env variable, but I got an error stating that the latest supported version was 115.something

**Comment by soulgalore** [comment]
Strange. So I check https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ to see exact versions, and if I try for example latest 118 it works for me on a Mac:

`EDGEDRIVER_VERSION=118.0.2088.17 node install.js`

I've just released 117, hopefully that works fine for you!

**Comment by mspiess** [comment]
That worked. Thanks!
